// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisplayLogInfo(arg1) {
  return window['go']['main']['App']['DisplayLogInfo'](arg1);
}

export function SendInfo(arg1, arg2) {
  return window['go']['main']['App']['SendInfo'](arg1, arg2);
}

export function ValidateEmail(arg1) {
  return window['go']['main']['App']['ValidateEmail'](arg1);
}
