// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvContainsEmailData():Promise<boolean>;

export function DisplayLogInfo(arg1:string):Promise<void>;

export function RunScan():Promise<void>;

export function SendInfo(arg1:string,arg2:string):Promise<void>;

export function ValidateEmail(arg1:string):Promise<boolean>;
