// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvContainsEmailData() {
  return window['go']['main']['App']['CheckEnvContainsEmailData']();
}

export function DisplayLogInfo(arg1) {
  return window['go']['main']['App']['DisplayLogInfo'](arg1);
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function RunScan() {
  return window['go']['main']['App']['RunScan']();
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function SendInfo(arg1, arg2) {
  return window['go']['main']['App']['SendInfo'](arg1, arg2);
}

export function ValidateEmail(arg1) {
  return window['go']['main']['App']['ValidateEmail'](arg1);
}
